name: meu-primeiro-workflow_dispatch

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mais-ou-menos-boas-vindas:
    runs-on: ubuntu-latest
    steps:
      - name: Cumprimentar a turma
        run: echo "Olá, GitHub Actions!"
      - name: Listar arquivos
        run: ls -la